status and price
alexross2502/client pull request #40
Opened 2023-04-20 13:27 UTC by alexross2502

2023-04-20 15:02 UTC, nik-clockwise requested changes

2023-04-20 15:02 UTC, nik-clockwise commented on src/AdminComponents/Components/ReservationPage/ReservationPage.tsx
> +                    <TableCell align="left">{row.price / 100}</TableCell>
выисление цены для показа лучше делать не в шаблоне, а отдельно в компоненте

2023-04-20 15:02 UTC, nik-clockwise commented on src/AdminComponents/Components/ReservationPage/reservationSave.tsx
> +      let clients = await Api.getAll("clients/true");
Что-то совсем не понятно что тут проиходит. 
Предполагаю что это какой-то параметр, параметры для GET запросов обычно передают через query-string, это удобно, а роутинг оставим для группировки роутов

2023-04-20 15:02 UTC, nik-clockwise commented on src/AdminComponents/Components/TownsPage/TownsPage.tsx
> +                    <TableCell align="left">{row.tariff / 100}</TableCell>
логика в шаблоне

2023-04-20 15:02 UTC, nik-clockwise commented on src/ClientAccount/ClientAccount.tsx
> +                    <TableCell align="left">{row.price / 100}</TableCell>
логика в шаблоне

2023-04-20 15:02 UTC, nik-clockwise commented on src/MasterAccount/MasterAccount.tsx
> +                      <TableCell align="left">{row.price / 100}</TableCell>
логика в шаблоне

2023-04-20 15:02 UTC, nik-clockwise commented on src/utils/constants.tsx
> +export const statusVariant = ["canceled", "confirmed", "executed"];
Лучше испоьзовать enumы

2023-04-24 06:13 UTC, alexross2502 commented on src/AdminComponents/Components/ReservationPage/reservationSave.tsx
> +      let clients = await Api.getAll("clients/true");
єто она и была, а не отдельный роут новый. Переделал, чтоб внешний вид єтой строки больше подходит под шаблонный

2023-04-24 06:16 UTC, alexross2502 commented on src/AdminComponents/Components/ReservationPage/ReservationPage.tsx
> +                    <TableCell align="left">{row.price / 100}</TableCell>
+

2023-04-24 06:27 UTC, alexross2502 commented on src/AdminComponents/Components/TownsPage/TownsPage.tsx
> +                    <TableCell align="left">{row.tariff / 100}</TableCell>
+

2023-04-24 06:28 UTC, alexross2502 commented on src/ClientAccount/ClientAccount.tsx
> +                    <TableCell align="left">{row.price / 100}</TableCell>
+

2023-04-24 06:28 UTC, alexross2502 commented on src/MasterAccount/MasterAccount.tsx
> +                      <TableCell align="left">{row.price / 100}</TableCell>
+

2023-04-24 06:52 UTC, alexross2502 commented on src/utils/constants.tsx
> +export const statusVariant = ["canceled", "confirmed", "executed"];
+

2023-04-24 09:49 UTC, nik-clockwise requested changes

2023-04-24 09:49 UTC, nik-clockwise commented on src/AdminComponents/Components/ReservationPage/ReservationPage.tsx
> +        el.price /= 100;
мне кажется всё таки лучше сделать отдельную функцию, которая конвертирует цену в "человекопонятную" и выывать её в шаблоне передавая базовую цену

2023-04-24 09:49 UTC, nik-clockwise commented on src/AdminComponents/Components/ReservationPage/reservationSave.tsx
> +        "masters/?mailConfirmation=true&adminApprove=true"
квери параметры надо бы прокидывать отдельными параметрави в функцию getAll, например getAll('url', { mailConfirmation: true, adminApprove: true })

2023-04-24 09:49 UTC, nik-clockwise commented on src/AdminComponents/Components/TownsPage/TownsPage.tsx
> +        el.tariff /= 100;
.

2023-04-24 09:49 UTC, nik-clockwise commented on src/ClientAccount/ClientAccount.tsx
> +        el.price /= 100;
.

2023-04-24 09:49 UTC, nik-clockwise commented on src/MasterAccount/MasterAccount.tsx
> +        el /= 100;
.

2023-04-24 09:49 UTC, nik-clockwise commented on src/utils/priceCalculator.tsx
Это где-то используется? Лучше назвать это не калькулятор, а форматтер. Если я правильно понял мы переводим копейки в грн($)?

2023-04-24 10:25 UTC, alexross2502 commented on src/utils/priceCalculator.tsx
переименовал

2023-04-24 10:27 UTC, alexross2502 commented on src/AdminComponents/Components/ReservationPage/ReservationPage.tsx
> +        el.price /= 100;
+

2023-04-24 10:29 UTC, alexross2502 commented on src/AdminComponents/Components/TownsPage/TownsPage.tsx
> +        el.tariff /= 100;
+

2023-04-24 10:32 UTC, alexross2502 commented on src/MasterAccount/MasterAccount.tsx
> +        el /= 100;
+

2023-04-24 10:32 UTC, alexross2502 commented on src/ClientAccount/ClientAccount.tsx
> +        el.price /= 100;
+

2023-04-24 10:52 UTC, alexross2502 commented on src/AdminComponents/Components/ReservationPage/reservationSave.tsx
> +        "masters/?mailConfirmation=true&adminApprove=true"
+

2023-04-24 11:54 UTC, nik-clockwise approved these changes

2023-04-24 12:16 UTC, merged