add: addModals
alexross2502/client pull request #45
Opened 2023-04-25 14:42 UTC by alexross2502

2023-04-26 12:04 UTC, nik-clockwise requested changes

2023-04-26 12:04 UTC, nik-clockwise commented on src/AdminComponents/Components/ClientsPage/clientSave.tsx
> +        props.result({ type: "success", message: "Успешно" });
Давай напишем более логические сообщения типа "Данные сохранены успешно". Это везде надо глянуть, в пределах ПРа

2023-04-26 12:04 UTC, nik-clockwise commented on src/AdminComponents/Components/TownsPage/townSave.tsx
> +                  background: "rgba(180,58,58,1)",
стили лучше выносить из шаблона, хотя бы в начало этого файла как const и называть так что бы было понятно к какому компоненту стили. Так код шаблона будет меньше и читаемей

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/Header/Header.tsx
> +                  onClick={props.order}></Tab>
лучше пропсы деструктурировать сразу на входе в функцию

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/ModalAvailableMasters/AvailableMastersForm.tsx
> +  const [master, orderData] = [props.data, props.orderData];
это можно сделать сразу на входе в функцию деструктурировав пропс { data: master, orderData }

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/ModalOrder/ModalOrder.tsx
> +        props.next({
тоже лучше деструктурировать пропсы

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/ModalOrder/ModalOrder.tsx
> +                background: "rgba(180,58,58,1)",
стили

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +        props.result({
деструктуризация пропсов

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +const ModalRegistration = (props) => {
и можно типы описать, что бы было понятно что ожидает компонент и как с этим работать

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +              backgroundColor: "#a0a0a0",
стили

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/Modals/ChangeStatusModal.tsx
> +const ChangeStatusModal = (props) => {
пропсы

2023-04-26 12:04 UTC, nik-clockwise commented on src/Components/Modals/UpdatePasswordModal.tsx
> +                      props.result({
пропсы

2023-04-26 12:45 UTC, alexross2502 commented on src/AdminComponents/Components/TownsPage/townSave.tsx
> +                  background: "rgba(180,58,58,1)",
кнопки повыносил в отдельный файл, остальное частоиспользуемое потихоньку тоже буду выносить как наткнусь

2023-04-26 12:53 UTC, alexross2502 commented on src/Components/ModalOrder/ModalOrder.tsx
> +                background: "rgba(180,58,58,1)",
+

2023-04-26 12:54 UTC, alexross2502 commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +              backgroundColor: "#a0a0a0",
+

2023-04-26 13:23 UTC, alexross2502 commented on src/Components/Header/Header.tsx
> +                  onClick={props.order}></Tab>
+

2023-04-26 13:28 UTC, alexross2502 commented on src/Components/ModalOrder/ModalOrder.tsx
> +        props.next({
+

2023-04-26 13:52 UTC, alexross2502 commented on src/Components/ModalOrder/ModalOrder.tsx
> +        props.next({
на входе функций деструктуризацию понимаю и сделал. Тут не понимаю, что деструктурировать. Я собираю в 3 местах данные, которые мне нужны будут дальше, присваиваю им нужные дальше имена, которые в большинстве случаев отличаются от имен в изначальных местах

2023-04-26 13:53 UTC, alexross2502 commented on src/Components/ModalOrder/ModalOrder.tsx
> +        props.next({
+

2023-04-26 14:05 UTC, alexross2502 commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +const ModalRegistration = (props) => {
+

2023-04-26 14:05 UTC, alexross2502 commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +        props.result({
+

2023-04-26 14:24 UTC, alexross2502 commented on src/Components/Modals/ChangeStatusModal.tsx
> +const ChangeStatusModal = (props) => {
+

2023-04-27 05:23 UTC, alexross2502 commented on src/Components/Modals/UpdatePasswordModal.tsx
> +                      props.result({
+

2023-04-27 05:46 UTC, alexross2502 commented on src/Components/ModalAvailableMasters/AvailableMastersForm.tsx
> +  const [master, orderData] = [props.data, props.orderData];
+

2023-04-27 05:59 UTC, alexross2502 commented on src/AdminComponents/Components/ClientsPage/clientSave.tsx
> +        props.result({ type: "success", message: "Успешно" });
прошелся по ПР

2023-04-27 10:53 UTC, nik-clockwise requested changes

2023-04-27 10:53 UTC, nik-clockwise commented on src/AdminComponents/Components/MastersPage/MastersPage.tsx
> +          props={[itemForUpdatePassword[0], itemForUpdatePassword[1]]}
А зачем мы тут массив передаем? Можно же объект и типизировать его, что бы опнимать что прходит в компонент

2023-04-27 10:53 UTC, nik-clockwise commented on src/Components/Header/Header.tsx
> +type IProps = {
"I" обычно ставить для интерфейсов, что ыб по названию (файла, класса) понимать что это интерфейс. С типами наверно можно T или без приставки. Дело общепринятости, если интересно - надо почитать

2023-04-27 10:53 UTC, nik-clockwise commented on src/Components/Header/Header.tsx
> +  const { authorization, order, registration } = props;
деструктуризацию лучше сделать сразу во входных параметрах, зачем елать лишнюю строчку?

2023-04-27 10:53 UTC, nik-clockwise commented on src/Components/ModalAuthorization/ModalAuthorization.tsx
> +  const { onClose, result } = props;
.

2023-04-27 10:53 UTC, nik-clockwise commented on src/Components/Modals/ErrorAndSuccessModal.tsx
> +    bgcolor: type === "success" ? "#f3f7c8" : "#FF0000",
цвета эти наврено уже егде-то есть в проекте, надо бы переиспользовать их

2023-04-27 11:43 UTC, alexross2502 commented on src/AdminComponents/Components/MastersPage/MastersPage.tsx
> +          props={[itemForUpdatePassword[0], itemForUpdatePassword[1]]}
+

2023-04-27 11:53 UTC, alexross2502 commented on src/Components/Header/Header.tsx
> +type IProps = {
+

2023-04-27 11:53 UTC, alexross2502 commented on src/Components/Header/Header.tsx
> +  const { authorization, order, registration } = props;
+

2023-04-27 11:53 UTC, alexross2502 commented on src/Components/ModalAuthorization/ModalAuthorization.tsx
> +  const { onClose, result } = props;
+

2023-04-27 11:54 UTC, alexross2502 commented on src/Components/Modals/ErrorAndSuccessModal.tsx
> +    bgcolor: type === "success" ? "#f3f7c8" : "#FF0000",
+

2023-04-27 12:12 UTC, merged

2023-04-27 12:43 UTC, nik-clockwise commented on src/Components/ModalRegistration/ModalRegistration.tsx
> +type TProps = {
Для всех модалок можно сделать один тип, с необязательынм параметром и generic типом возможно. Но переделывать уже не надо, пусть так будет. Просто знай что было бы хорошо переиспользовать 1 тип в твоем случае

2023-04-27 12:43 UTC, nik-clockwise commented
Не спеши мержить в следующий раз