Cloudinary
alexross2502/client pull request #47
Opened 2023-04-27 12:14 UTC by alexross2502

2023-05-02 15:06 UTC, nik-clockwise requested changes

2023-05-02 15:06 UTC, nik-clockwise commented on src/Components/ModalOrder/ModalOrder.tsx
> +    data.image = formData;
Наверно лучше назвать images и на срвере тоже, так более понятно что происходит

2023-05-04 11:20 UTC, alexross2502 commented on src/Components/ModalOrder/ModalOrder.tsx
> +    data.image = formData;
+

2023-05-05 07:40 UTC, nik-clockwise approved these changes

2023-05-05 09:01 UTC, merged