Sort
alexross2502/client pull request #51
Opened 2023-05-05 11:30 UTC by alexross2502

2023-05-05 11:52 UTC, nik-clockwise requested changes

2023-05-05 11:52 UTC, nik-clockwise commented on src/utils/constants.tsx
> +export enum SORTED_FIELD {
для каждой сущьности нужно сделать отдельный набор полей для сортировки, если эти enums про это

2023-05-05 13:50 UTC, alexross2502 commented on src/utils/constants.tsx
> +export enum SORTED_FIELD {
Єто имеется ввиду?
+убрал сортировку по id, как решили час назад

2023-05-08 08:39 UTC, nik-clockwise approved these changes

2023-05-08 08:47 UTC, merged